### ISSUE TITLE
option to skip plugin execution

### ISSUE THREAD

**Issue by romani** [mojohaus/xml-maven-plugin#2]
Almost all plugins have a option to skip execution without changes to pom.xml  that is very useful to and let users have one configuration and run build by sub-phases (not as monolith phase).
Additionally it helps to skip plugin from running till bug fix is not released.

Examples of how our project do control of verify phase - https://github.com/checkstyle/checkstyle/blob/master/.travis.yml#L22.

Additional problem we found is that plugin rely on internet access to get xsd and dtd files, that make build unstable and we would rather move validation of xml files to separate build phase. I will try to show place there en example (do not have now as I always relaunch build to make it green).

Example of failure from users: https://github.com/checkstyle/checkstyle/issues/2191#issuecomment-142892825

**Comment by jochenw** [comment]
I have added a parameter "skip" with default "${xml.skip}". (Not yet committed, because I am waiting for the required permissions.)

The problem that I do see here: This parameter applies to both "xml:validate" (aka ValidateMojo), and "xml:transform" (aka TransformMojo), which might be a bit confusing, and/or misleading.

**Comment by jochenw** [comment]
Just committed, closing.

**Comment by romani** [comment]
is it possible to make a release of this plugin ? please share plan for next release.

**Comment by vramik** [comment]
+1 for releasing new version with this fix

**Comment by khmarbaise** [comment]
Started release VOTE...
