### ISSUE TITLE
Add github report to site generation.

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/xml-maven-plugin#9]

**Comment by jochenw** [comment]
Karl-Heinz, can you provide an example of what I've got to do?

**Comment by khmarbaise** [comment]
For example: http://www.mojohaus.org/build-helper-maven-plugin/github-report.html

**Comment by jochenw** [comment]
Okay, thanks!

**Comment by rosslamont** [comment]
Looks to me like this is now working, but the current report is not showing lots of recently closed issues, because they don't have an associated milestone.  I don't appear to have rights to append the milestone to those closed issues.

Also, are these changes worthy of moving to 1.1 rather than 1.0.2?  

Finally, can I call a vote on a release or is that something that only committers do?

**Comment by jochenw** [comment]
Hi, Ross,

why did you remove the information from changes.xml?

Thanks,

Jochen

**Comment by rosslamont** [comment]
Hi Jochen,

All that information is in the GitHub report (I only removed the 1.0.2 stuff which should be all recorded in GitHub).  I checked around some other pre-github projects and it seems that people either use the changes report or the GitHub report, so I also turned off the changes report. 

Personally I think keeping the changes report in, but making a clean cutover to the GitHub report has some value, but I can see that would be confusing.

Cheers
Ross

**Comment by jochenw** [comment]
Hi, Ross,

okay, I was just asking. Lets see, how this turns out. Might be, I return
to that later, because personally I am all in favour of having things in
one place. (We are working on the sources anyways, and that's where
changes.xml is located.)

Jochen
